version: "3.9"
services:
  redis:
    container_name: rediscrashcourse
    image: "redis/redis-stack"
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  node:
    container_name: node_rediscrashcourse
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run load all && npm run dev"
    depends_on:
      - redis
    ports:
      - 8081:8081
    environment:
      - CRASH_COURSE_CONFIG_FILE=config_docker.json